# Generated by Django 3.2.7 on 2021-09-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_seats', models.IntegerField()),
                ('stu_rn', models.IntegerField()),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_marks', models.FloatField()),
                ('Lec_name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30)),
                ('dept_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_rn', models.IntegerField()),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_marks', models.FloatField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('Department', models.ManyToManyField(to='App1.Department')),
            ],
        ),
    ]
